name: Publish Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Or specify your target Python version

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install twine

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No need for with: password: ${{ secrets.PYPI_API_TOKEN }}
      # when using trusted publishing (id-token: write permission)
      # Ensure your PyPI project is configured for trusted publishing.
      # If not using trusted publishing, uncomment the line below
      # and ensure PYPI_API_TOKEN secret is set.
      # with:
      #   password: ${{ secrets.PYPI_API_TOKEN }} 