MODEL_FLAGS = [
    # --- Main model ---
    {
        "name": "model",
        "description": "Specify the model to use for the main chat",
        "category": "Main model",
        "value_type": "string",
        "default_value": None,
        "requires_value": True,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    # --- Model settings ---
    {
        "name": "list-models",
        "description": "List known models which match the (partial) MODEL name",
        "category": "Model settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "model-settings-file",
        "description": "Specify a file with aider model settings for unknown models",
        "category": "Model settings",
        "value_type": "path",
        "default_value": ".aider.model.settings.yml",
        "requires_value": True,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "model-metadata-file",
        "description": "Specify a file with context window and costs for unknown models",
        "category": "Model settings",
        "value_type": "path",
        "default_value": ".aider.model.metadata.json",
        "requires_value": True,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "alias",
        "description": "Add a model alias (can be used multiple times)",
        "category": "Model settings",
        "value_type": "string_multiple",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "reasoning-effort",
        "description": "Set the reasoning_effort API parameter (default: not set)",
        "category": "Model settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "thinking-tokens",
        "description": "Set the thinking token budget for models that support it (default: not set)",
        "category": "Model settings",
        "value_type": "integer",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "verify-ssl",
        "description": "Verify the SSL cert when connecting to models (default: True)",
        "category": "Model settings",
        "value_type": "boolean_explicit",
        "choices": ["--verify-ssl", "--no-verify-ssl"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "timeout",
        "description": "Timeout in seconds for API calls (default: None)",
        "category": "Model settings",
        "value_type": "integer",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "edit-format",
        "description": "Specify what edit format the LLM should use (default depends on model)",
        "category": "Model settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "architect",
        "description": "Use architect edit format for the main chat",
        "category": "Model settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "auto-accept-architect",
        "description": "Enable/disable automatic acceptance of architect changes (default: True)",
        "category": "Model settings",
        "value_type": "boolean_explicit",
        "choices": ["--auto-accept-architect", "--no-auto-accept-architect"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "weak-model",
        "description": "Specify the model to use for commit messages and chat history summarization (default depends on –model)",
        "category": "Model settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "editor-model",
        "description": "Specify the model to use for editor tasks (default depends on –model)",
        "category": "Model settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "editor-edit-format",
        "description": "Specify the edit format for the editor model (default: depends on editor model)",
        "category": "Model settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "show-model-warnings",
        "description": "Only work with models that have meta-data available (default: True)",
        "category": "Model settings",
        "value_type": "boolean_explicit",
        "choices": ["--show-model-warnings", "--no-show-model-warnings"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "check-model-accepts-settings",
        "description": "Check if model accepts settings like reasoning_effort/thinking_tokens (default: True)",
        "category": "Model settings",
        "value_type": "boolean_explicit",
        "choices": [
            "--check-model-accepts-settings",
            "--no-check-model-accepts-settings",
        ],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "max-chat-history-tokens",
        "description": "Soft limit on tokens for chat history, after which summarization begins.",
        "category": "Model settings",
        "value_type": "integer",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
