OTHER_FLAGS = [
    {
        "name": "file",
        "description": "Specify a file to edit (can be used multiple times)",
        "category": "Other settings",
        "value_type": "path_multiple",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "yes-always",
        "description": "Always say yes to every confirmation",
        "category": "Other settings",
        "value_type": "boolean",
        "default_value": None,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "verbose",
        "description": "Enable verbose output",
        "category": "Other settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "config",
        "description": "Specify the config file",
        "category": "Other settings",
        "value_type": "path",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "disable-playwright",
        "description": "Disable playwright for web scraping (default: False)",
        "category": "Other settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "read",
        "description": "Read and summarize the content of the specified FILE or URL before starting the chat",
        "category": "Other settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "vim",
        "description": "Enable vim keybindings for input (default: False)",
        "category": "Other settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "chat-language",
        "description": "Specify the language for chat using ISO 639-1 code (default: en)",
        "category": "Other settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": "en",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "load",
        "description": "Load a chat session from a file",
        "category": "Other settings",
        "value_type": "path",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "encoding",
        "description": "Specify the encoding for reading/writing files (default: utf-8)",
        "category": "Other settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": "utf-8",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "line-endings",
        "description": "Specify the line endings for writing files (auto, lf, crlf, cr) (default: auto)",
        "category": "Other settings",
        "value_type": "choice",
        "choices": ["auto", "lf", "crlf", "cr"],
        "requires_value": True,
        "default_value": "auto",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "env-file",
        "description": "Specify a .env file to load environment variables from",
        "category": "Other settings",
        "value_type": "path",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "suggest-shell-commands",
        "description": "Enable/disable LLM suggested shell commands (default: True)",
        "category": "Other settings",
        "value_type": "boolean_explicit",
        "choices": ["--suggest-shell-commands", "--no-suggest-shell-commands"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "fancy-input",
        "description": "Enable/disable fancy input mode with real-time syntax highlighting (default: True)",
        "category": "Other settings",
        "value_type": "boolean_explicit",
        "choices": ["--fancy-input", "--no-fancy-input"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "multiline",
        "description": "Enable/disable multiline input mode (default: True)",
        "category": "Other settings",
        "value_type": "boolean_explicit",
        "choices": ["--multiline", "--no-multiline"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "notifications",
        "description": "Enable/disable desktop notifications (default: False)",
        "category": "Other settings",
        "value_type": "boolean_explicit",
        "choices": ["--notifications", "--no-notifications"],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "notifications-command",
        "description": "Specify a custom command for notifications",
        "category": "Other settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "detect-urls",
        "description": "Enable/disable automatic detection and scraping of URLs in chat (default: True)",
        "category": "Other settings",
        "value_type": "boolean_explicit",
        "choices": ["--detect-urls", "--no-detect-urls"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "editor",
        "description": "Specify the editor to use for opening files (default: $EDITOR or $VISUAL)",
        "category": "Other settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "shell-completions",
        "description": "Install or remove shell completions (bash, zsh, fish)",
        "category": "Other settings",
        "value_type": "choice",
        "choices": ["bash", "zsh", "fish"],
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
