MODES_FLAGS = [
    {
        "name": "message",
        "description": "Specify a single message to send the LLM, process reply then exit (disables chat mode)",
        "category": "Modes",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "message-file",
        "description": "Specify a file containing the message to send the LLM, process reply, then exit",
        "category": "Modes",
        "value_type": "path",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "gui",
        "description": "Run aider in your browser (default: False)",
        "category": "Modes",
        "value_type": "boolean_explicit",
        "choices": ["--gui", "--no-gui"],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "copy-paste",
        "description": "Enable copy-paste mode (default: False)",
        "category": "Modes",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "apply",
        "description": "Apply the changes from the given FILE or from STDIN, then exit",
        "category": "Modes",
        "value_type": "path",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "apply-clipboard-edits",
        "description": "Apply edits from the system clipboard (default: False)",
        "category": "Modes",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "exit",
        "description": "Exit after the first response from the LLM",
        "category": "Modes",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "show-repo-map",
        "description": "Show the repo map and exit (default: False)",
        "category": "Modes",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "show-prompts",
        "description": "Show all system prompts and exit (default: False)",
        "category": "Modes",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
