API_FLAGS = [
    {
        "name": "openai-api-key",
        "description": "Specify the OpenAI API key",
        "category": "API Keys and settings",
        "value_type": "string",
        "default_value": None,
        "requires_value": True,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "anthropic-api-key",
        "description": "Specify the Anthropic API key",
        "category": "API Keys and settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "openai-api-base",
        "description": "Specify the api base url",
        "category": "API Keys and settings",
        "value_type": "string",
        "default_value": None,
        "requires_value": True,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "openai-api-type",
        "description": "(deprecated, use –set-env OPENAI_API_TYPE=<value>)",
        "category": "API Keys and settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": True,
        "wizard_visible": True,
    },
    {
        "name": "openai-api-version",
        "description": "(deprecated, use –set-env OPENAI_API_VERSION=<value>)",
        "category": "API Keys and settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": True,
        "wizard_visible": True,
    },
    {
        "name": "openai-api-deployment-id",
        "description": "(deprecated, use –set-env OPENAI_API_DEPLOYMENT_ID=<value>)",
        "category": "API Keys and settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": True,
        "wizard_visible": True,
    },
    {
        "name": "openai-organization-id",
        "description": "(deprecated, use –set-env OPENAI_ORGANIZATION=<value>)",
        "category": "API Keys and settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": True,
        "wizard_visible": True,
    },
    {
        "name": "set-env",
        "description": "Set an environment variable (to control API settings, can be used multiple times)",
        "category": "API Keys and settings",
        "value_type": "string_multiple",
        "requires_value": True,
        "default_value": "[]",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "api-key",
        "description": "Set an API key for a provider (eg: –api-key provider=<key>)",
        "category": "API Keys and settings",
        "value_type": "string_multiple",
        "default_value": "[]",
        "requires_value": True,
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
