HISTORY_FLAGS = [
    {
        "name": "input-history-file",
        "description": "Specify the chat input history file (default: .aider.input.history)",
        "category": "History Files",
        "value_type": "path",
        "requires_value": True,
        "default_value": ".aider.input.history",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "chat-history-file",
        "description": "Specify the chat history file (default: .aider.chat.history.md)",
        "category": "History Files",
        "value_type": "path",
        "requires_value": True,
        "default_value": ".aider.chat.history.md",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "restore-chat-history",
        "description": "Restore the previous chat history messages (default: False)",
        "category": "History Files",
        "value_type": "boolean_explicit",
        "choices": ["--restore-chat-history", "--no-restore-chat-history"],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "llm-history-file",
        "description": "Log the conversation with the LLM to this file (for example, .aider.llm.history)",
        "category": "History Files",
        "value_type": "path",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
