GIT_FLAGS = [
    # --- Git settings ---
    {
        "name": "auto-commits",
        "description": "Enable/disable auto commit of LLM changes (default: True)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--auto-commits", "--no-auto-commits"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "dirty-commits",
        "description": "Enable/disable commits when repo is found dirty (default: True)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--dirty-commits", "--no-dirty-commits"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "git",
        "description": "Enable/disable looking for a git repo (default: True)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--git", "--no-git"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "dry-run",
        "description": "Perform a dry run without modifying files (default: False)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--dry-run", "--no-dry-run"],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "gitignore",
        "description": "Enable/disable adding .aider* to .gitignore (default: True)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--gitignore", "--no-gitignore"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "aiderignore",
        "description": "Specify the aider ignore file (default: .aiderignore in git root)",
        "category": "Git settings",
        "value_type": "path",
        "requires_value": True,
        "default_value": ".aiderignore",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "subtree-only",
        "description": "Only consider files in the current subtree of the git repository",
        "category": "Git settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "attribute-author",
        "description": "Attribute aider code changes in the git author name (default: True)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--attribute-author", "--no-attribute-author"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "attribute-committer",
        "description": "Attribute aider commits in the git committer name (default: True)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--attribute-committer", "--no-attribute-committer"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "attribute-commit-message-author",
        "description": "Prefix commit messages with ‘aider: ‘ if aider authored the changes (default: False)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": [
            "--attribute-commit-message-author",
            "--no-attribute-commit-message-author",
        ],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "attribute-commit-message-committer",
        "description": "Prefix all commit messages with ‘aider: ‘ (default: False)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": [
            "--attribute-commit-message-committer",
            "--no-attribute-commit-message-committer",
        ],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "attribute-co-authored-by",
        "description": "Attribute aider edits using the Co-authored-by trailer in the commit message (default: False)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--attribute-co-authored-by", "--no-attribute-co-authored-by"],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "git-commit-verify",
        "description": "Enable/disable git pre-commit hooks with –no-verify (default: False)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--git-commit-verify", "--no-git-commit-verify"],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "commit",
        "description": "Commit all pending changes with a suitable commit message, then exit",
        "category": "Git settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "commit-prompt",
        "description": "Specify a custom prompt for generating commit messages",
        "category": "Git settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "skip-sanity-check-repo",
        "description": "Skip the sanity check for the git repository (default: False)",
        "category": "Git settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "watch-files",
        "description": "Enable/disable watching files for ai coding comments (default: False)",
        "category": "Git settings",
        "value_type": "boolean_explicit",
        "choices": ["--watch-files", "--no-watch-files"],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
