REPOMAP_FLAGS = [
    {
        "name": "map-tokens",
        "description": "Suggested number of tokens to use for repo map, use 0 to disable",
        "category": "Repomap settings",
        "value_type": "integer",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "map-refresh",
        "description": "Control how often the repo map is refreshed. Options: auto, always, files, manual (default: auto)",
        "category": "Repomap settings",
        "value_type": "choice",
        "choices": ["auto", "always", "files", "manual"],
        "requires_value": True,
        "default_value": "auto",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "map-multiplier-no-files",
        "description": "Multiplier for map tokens when no files are specified (default: 2)",
        "category": "Repomap settings",
        "value_type": "integer",
        "requires_value": True,
        "default_value": "2",
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
