OUTPUT_FLAGS = [
    {
        "name": "dark-mode",
        "description": "Use colors suitable for a dark terminal background (default: False)",
        "category": "Output settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "light-mode",
        "description": "Use colors suitable for a light terminal background (default: False)",
        "category": "Output settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "stream",
        "description": "Enable/disable streaming responses (default: True)",
        "category": "Output settings",
        "value_type": "boolean_explicit",
        "choices": ["--stream", "--no-stream"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "pretty",
        "description": "Enable/disable pretty, colorized output (default: True)",
        "category": "Output settings",
        "value_type": "boolean_explicit",
        "choices": ["--pretty", "--no-pretty"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "show-diffs",
        "description": "Show diffs when committing changes (default: False)",
        "category": "Output settings",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "user-input-color",
        "description": "Set the color for user input (default: #00cc00)",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": "#00cc00",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "tool-output-color",
        "description": "Set the color for tool output (default: None)",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "tool-error-color",
        "description": "Set the color for tool error messages (default: #FF2222)",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": "#FF2222",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "tool-warning-color",
        "description": "Set the color for tool warning messages (default: #FFA500)",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": "#FFA500",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "assistant-output-color",
        "description": "Set the color for assistant output (default: #0088ff)",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": "#0088ff",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "completion-menu-color",
        "description": "Set the color for the completion menu",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "completion-menu-bg-color",
        "description": "Set the background color for the completion menu",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "completion-menu-current-color",
        "description": "Set the color for the current item in the completion menu",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "completion-menu-current-bg-color",
        "description": "Set the background color for the current item in the completion menu",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "code-theme",
        "description": "Set the markdown code theme (default: default, see Pygments styles)",
        "category": "Output settings",
        "value_type": "string",
        "requires_value": True,
        "default_value": "default",
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
