UPGRADING_FLAGS = [
    {
        "name": "version",
        "description": "Show the version number and exit",
        "category": "Upgrading",
        "value_type": "boolean",
        "default_value": None,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "upgrade",
        "description": "Upgrade aider to the latest version from PyPI",
        "category": "Upgrading",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "just-check-update",
        "description": "Just check for an update, print message and exit (default: False)",
        "category": "Upgrading",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "check-update",
        "description": "Check for an update, print message and continue (default: True)",
        "category": "Upgrading",
        "value_type": "boolean_explicit",
        "choices": ["--check-update", "--no-check-update"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "show-release-notes",
        "description": "Show release notes when upgrading (default: True)",
        "category": "Upgrading",
        "value_type": "boolean_explicit",
        "choices": ["--show-release-notes", "--no-show-release-notes"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "install-main-branch",
        "description": "Install the latest version of aider from the main branch on github",
        "category": "Upgrading",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
