FIXING_FLAGS = [
    {
        "name": "auto-lint",
        "description": "Enable/disable automatic linting after changes (default: True)",
        "category": "Fixing and committing",
        "value_type": "boolean_explicit",
        "choices": ["--auto-lint", "--no-auto-lint"],
        "default_value": True,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "lint-cmd",
        "description": 'Specify lint commands for languages, eg: "python: flake8" (multiple)',
        "category": "Fixing and committing",
        "value_type": "string_multiple",
        "requires_value": True,
        "default_value": "[]",
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "lint",
        "description": "Lint and show errors for specified files or all files in git repo",
        "category": "Fixing and committing",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "test-cmd",
        "description": "Specify the command to run tests",
        "category": "Fixing and committing",
        "value_type": "string",
        "requires_value": True,
        "default_value": None,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "auto-test",
        "description": "Enable/disable automatic testing after changes (default: False)",
        "category": "Fixing and committing",
        "value_type": "boolean_explicit",
        "choices": ["--auto-test", "--no-auto-test"],
        "default_value": False,
        "requires_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
    {
        "name": "test",
        "description": "Run tests using the test-cmd",
        "category": "Fixing and committing",
        "value_type": "boolean",
        "requires_value": False,
        "default_value": False,
        "is_deprecated": False,
        "wizard_visible": True,
    },
]
